default: &default
  oauth:
    base_url: https://oauth-latest.dev.lcip.org/v1
    client:
      id: <%= ENV['OAUTH_CLIENT_ID'] %>
      secret: <%= ENV['OAUTH_CLIENT_SECRET'] %>
    profile:
      base_url: https://latest.dev.lcip.org/profile/v1
  url2png:
    api_key: <%= ENV['URL2PNG_API_KEY'] %>
    secret_key: <%= ENV['URL2PNG_SECRET_KEY'] %>
  embedly:
    key: <%= ENV['EMBEDLY_KEY'] %>

development:
  <<: *default

test:
  <<: *default

development:
  <<: *default
