# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d3afc527d3485abfd593ddc97a87b94e2dd9747ffc1ea29709c3413f6aade8d223e260c084930f611558921c2044c7177faf0758a3605d0b1c0c9afd82f1197

test:
  secret_key_base: 84852f7149fd6e3e8a853b1954e489a0c5e08e0cf46fd74705f4b19d8572c9b2d7818eb11f0c9ea366ba26816da5545a01ba56a22a4281a3adfa48150cc30e60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
